### ISSUE TITLE
LUKS-encryption with LVM causes the disk-cloning to abort with error/warning: "The volume group setting is not found" - it should be ignored

### ISSUE THREAD

**Issue by marfeljoergsen** [stevenshiau/clonezilla#113]
Hi,

I can see a some stuff has been made for implementing support for LUKS-encryption. Since I normally make my backups to unencrypted disks, I'm not going to use that feature. I just downloaded the stable clonezilla ISO today ([stable - 3.1.3-16](https://clonezilla.org/downloads/download.php?branch=stable)) and forgive me if I didn't find the correct issue, I tried to search but will write my findings here instead.

### My setup (probably a bit unusual):
I have an encrypted boot-loader and one or two luks-partitions where at least 1 is LUKS2-encrypted with plausible deniability. It works such that my encrypted boot-loader automatically unlocks this special partition. But it also means this partition looks like it contains **_completely_** random data - as if it was/is unused/unformatted. 

### The problem:
I've tried several times to make a full disk cloned image, but clonezilla won't backup or clone the last two partitions I have. It won't allow me to override this behaviour - instead it comes up with warnings and errors: **_"/NOT_FOUND /dev/nvme0n1p9 (.....)" " + "///WARNING/// The volume group setting is not found" + "Unable to save LVM image"_**, seemingly because there is a "lvm" flag set for the partition AND it cannot find the corresponding partition (because it haven't been unlocked). So clonezilla thinks my partitions are corrupted and screwed (which they aren't if I unlock them properly). The output of "lvs" and "vgs" shows nothing. The "pvs" command shows nvme0n1p9 has "Fmt=lvm2" and the size is 909g.

### My understanding:
I'm firmly believe this problem is happening because at least one encrypted drive is LUKS2-encrypted and I didn't unlock it - which I'm guessing is also not possible at the moment, because: In order to unlock it properly, in addition to the passphrase, it's also necessary to provide the 4096-byte LUKS detached header-file. I'm guessing I can only supply a passphrase in the current clonezilla-version (although I didn't try it).

### What I tried (and did):
I was looking for way to "--force" so the cloning would complete despite the LVM-errors, but even when using the "advanced" options, I couldn't make it work (and I couldn't find the --force option, I suggest please put it back). Eventually I guessed (and still believe) that it would've worked if I used an older clonezilla version, which doesn't understand LUKS-encryption, so it would default to using "dd". Because I'm a bit in a hurry I took the easy solution which is:

`# partclone.dd -s /dev/nvme0n1p9 -o nvme0n1p9.dd -L n1p9.log`

And I'm running this now. I think the current clonezilla version is missing the "--force" option, so it ignores what it thinks is LVM-corrupted partitions... I've been using clonezilla for +10 years so I want it to be as useful and good as always and hope this report can help improving the software, thanks for great work!

**Comment by stevenshiau** [comment]
Thanks for your feedback.
If you can reproduce this issue in a VM which does not contain any classified data, please share the VM with us so that it's easier for us to reproduce this issue.

**Comment by marfeljoergsen** [comment]
Yes, I think I know how to do a similar setup that I can share, which will aid implementation and testing. I think I should've been more precise and written that I belive I'm running with [LVM on LUKS](https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LVM_on_LUKS ) such that I can unlock several volumes using a single passphrase and keyfile. To quote:

> Hence, the LVM is not visible until the block device is unlocked and the underlying volume structure is scanned and mounted. 

So I think this explains the error and why I had to resort to running partclone.dd directly. As mentioned I also used LUKS2 with detached header: `sudo cryptsetup luksFormat /dev/sdb --header luksheader.img` so I'm guessing I can reproduce the behaviour in a VM, I just need to get back to this later this month, hopefully within around 2 weeks as I'm a bit busy. I'll try to create a minimal example in a container and write an update later this month, thanks.

**Comment by marfeljoergsen** [comment]
Hi Steven. I think it was relatively easy for me to reproduce (apologize the delay, I've been busy with a new job). Although I don't 100% get the same error message I believe it's the same problem. The error message I now get is:

### ///WARNING/// The LVM physical volume setting was not found" + "Unable to save LVM image"

I'll share this zip-file (40 MB) which needs Virtualbox: https://drive.google.com/file/d/1RliH-sjEb8U16Dsi6_ItxUgL5iWxmJ2G/view?usp=drive_link (it's not running Alpine or any other Linux but with a more advanced setup with LUKS1-enabled GRUB-bootloader and LUKS2-header-file on that partition, it could be made so it automatically decrypts the second LUKS-partition and I have exactly that setup on some machines - it is however not needed here, for this simple demonstration of the problem).

### Instructions:
Inside Virtualbox, I created two disks (`Alpine Linux.vdi` and `Alpine Linux_CLONEZILLA...something.vdi`): The Alpine Linux.vdi has 5 partitions that more or less partition-wise looks like many of my machines with EFI-partition, NTFS/Windows-partitions and then something encrypted with Linux, very often I use LVM on top of LUKS. The other .vdi file (with just a single Linux-partition) is supposed to be the destination for the full disk clonezilla-image. I'm using "clonezilla-live-3.1.3-16-amd64.iso" if you want a 100% similar setup. Just boot up the VM. Once booted up, you should be able to see the two virtual disks as /dev/sd{a,b}. For your reference, I included the log-file in the simplest of the virtual disks. Here you can see the exact command I ran and the error message above. You should be able to reproduce the problem by running the same command...

As mentioned again, although I don't have the exact same error message this time I believe the problem is the same and that is that I believe that Clonezilla tries to see if the LVM-marked partition is "valid" which it cannot see unless the LUKS2-encrypted LVM-partition is unlocked and that both require the LUKS2-header file and the LUKS2-passprase (which is just "**_123_**"). I don't think Clonezilla in any case currently supports providing an external LUKS2-header file but it doesn't matter for me because in this case I don't want to unlock the LUKS2-encrypted LVM-partition before making the image. I need some kind of "--force" or "--ignore-errors" option so clonezilla won't do any validation but just perform a simple "dd"-copy and it doesn't even offer me the chance to do a simple "dd"-copy here... I also include a modified "history"-file so you can see which commands I ran to create this LUKS2-encrypted LVM-partition. Please let me know if there are any questions and I'll happily (and should be able to) reply relatively quick. Thanks!
