### ISSUE TITLE
clonezilla missing -n, --no-wait-before-exit in USAGE

### ISSUE THREAD

**Issue by tim-cyb** [stevenshiau/clonezilla#119]
Usage function for clonezilla command is missing `-n, --no-wait-before-exit` flag: https://github.com/stevenshiau/clonezilla/blob/cbdd5a5aa5eef76db8605a1e0b42536ec728ccca/sbin/clonezilla#L25-L37

Bash logic for the flag: https://github.com/stevenshiau/clonezilla/blob/cbdd5a5aa5eef76db8605a1e0b42536ec728ccca/sbin/clonezilla#L125

Spent a day trying to bypass "Press ENTER to continue..." at the very end of an unattended install Clonezilla solution before reboot would happen. Problem solved by adding `-n` to `ocs_opt` in `/tftpboot/nbi_img/pxelinux.cfg/default`.

Final result: `ocs_opt="-l en_US.UTF-8 -p reboot -k --skip-lite-menu -n select_in_client"`

Please add the missing flag `-n, --no-wait-before-exit` to usage.

**Comment by stevenshiau** [comment]
Added. Thanks for reporting this.

Steven
