### ISSUE TITLE
Incorrect prefix in grub.cfg

### ISSUE THREAD

**Issue by Joey3000** [stevenshiau/clonezilla#13]
Referring to the /EFI/boot/grub.cfg file (both in ISO and ZIP releases): The file currently has following content (clonezilla-live-2.4.2-32-amd64):

```
#
set prefix=/EFI/boot/
set default="0"
if loadfont $prefix/unicode.pf2; then
set gfxmode=auto
insmod efi_gop
insmod efi_uga
insmod gfxterm
terminal_output gfxterm
fi
set timeout="30"
set hidden_timeout_quiet=false

if background_image $prefix/ocswp-grub2.png; then
set color_normal=black/black
set color_highlight=magenta/black
else
set color_normal=cyan/blue
set color_highlight=white/blue
fi

# Since no network setting in the squashfs image, therefore if ip=, the network is disabled.

menuentry "Clonezilla live (Default settings, VGA 800x600)"{
search --set -f /live/vmlinuz
linux /live/vmlinuz boot=live union=overlay username=user config components quiet noswap edd=on nomodeset nodmraid noeject locales= keyboard-layouts= ocs_live_run="ocs-live-general" ocs_live_extra_param="" ocs_live_batch=no vga=788 ip= net.ifnames=0 nosplash i915.blacklist=yes radeonhd.blacklist=yes nouveau.blacklist=yes vmwgfx.enable_fbdev=1
initrd /live/initrd.img
}
[...]
```

__Issue__
There seem to be following issues with the `set prefix=/EFI/boot/` line at its beginning:

1. The `prefix` defines location of Grub's ‘/boot/grub’ directory - i.e. the directory, in which a platform-specific sub-directory is located which contains Grub modules, such as `search.mod`, `linux.mod`, etc., which are used in the `menuentry`. But those modules don't come with Clonezilla, so that those modules aren't found by Grub using that `prefix`. (Grub could just use its own version-specific modules instead. So, no need to define `prefix` at all.) See https://www.gnu.org/software/grub/manual/grub.html#prefix for information.

2. The slash at the end of the line results in a double slash in on subsequent use of the `prefix` variable in the script. E.g.:

```
if loadfont $prefix/unicode.pf2
```

expands to:

```
if loadfont /EFI/boot//unicode.pf2
```

Which results in wrong path.

__Proposal__
It looks like the `prefix` variable is only needed for script-internal use. Therefore, following suggestion:

1. Rename `prefix` to anything not related to Grub environment variables. So that it becomes a purely internal script variable.

2. Remove the slash at the end of `set ...=/EFI/boot/`

Thank you for this great project!

**Comment by stevenshiau** [comment]
Thanks. I have modified as you have mentioned.
Please give Clonezilla live >= 2.4.2-66 or 20151103-* a try.

Steven.

**Comment by Joey3000** [comment]
Thanks! I can confirm that this fixed the Grub menu. The only thing missing now is the background image appearance. I submitted https://github.com/stevenshiau/clonezilla/pull/19 for that.
