### ISSUE TITLE
Add package jc

### ISSUE THREAD

**Issue by don-rumata** [stevenshiau/clonezilla#130]
Hi! Could you please add [jc](https://packages.debian.org/testing/jc) in your projects (Clonezilla/DRBL)?

**Comment by stevenshiau** [comment]
Thanks for your feedback. Will do that in the next testing release.

Steven

**Comment by stevenshiau** [comment]
The package jc was added in Clonezilla live >= 3.2.0-29 or 20241226-*. Please give it a try and let us know the results.
Thanks.

Steven

**Comment by don-rumata** [comment]
Hi, everything is working!

https://asciinema.org/a/I377kv62xZwSVPplvQGLi4CuU

**Comment by stevenshiau** [comment]
Great. Thanks for your confirmation.

Steven
