### ISSUE TITLE
Error: The resize command has been removed in parted 3.0

### ISSUE THREAD

**Issue by quozl** [stevenshiau/clonezilla#16]
When restoredisk has finished on an EFI partition, an error is reported;

```
Now tuning the file system size on partition /dev/mmcblk0p1 to fit the partition size...
Running: ocs-resize-part  --batch /dev/mmcblk0p1
Running: parted -s /dev/mmcblk0 resize p1 1049kB 538MB
Error: The resize command has been removed in parted 3.0
```

The error on the last line is on screen, but not in /var/log/clonezilla.log.

Perhaps because the check for resize in the ```parted --help``` output detects the new resizepartition command.

Seen on clonezilla-live-20151012-wily-amd64.iso

**Comment by stevenshiau** [comment]
Thanks. I have implemented fatresize instead of parted to deal with FAT.

Steven.
