### ISSUE TITLE
ocs-chnthn-functions does not work correctly with new net-tools version

### ISSUE THREAD

**Issue by notr1ch** [stevenshiau/clonezilla#21]
The script `scripts/sbin/ocs-chnthn-functions` uses `gen_hn_stream `to create a hostname to change a Windows hostname based on IP or MAC. This fails on recent versions of clonezilla since the ifconfig binary is from net-tools 2.10-alpha which has different output than the version from net-tools 1.x. The script is expecting output from net-tools 1.x, which results in the hostname not being set properly.

**Comment by stevenshiau** [comment]
Fixed in clonezilla 3.21.13. Thanks.

Steven
