### ISSUE TITLE
Question - Commercial/Business use?

### ISSUE THREAD

**Issue by kholyphoenix1** [stevenshiau/clonezilla#24]
Hello,

You can use Clonezilla so 'business'?
Or you need to acquire any license?

Thank you!

**Comment by stevenshiau** [comment]
Clonezilla is Free Software (GPL). You just follow the Free Software then you can use in the business freely (without charge). For the GPL license, check this:
https://www.gnu.org/licenses/gpl-3.0.en.html

Steven
