### ISSUE TITLE
create clonezilla live install iso from existing disk image

### ISSUE THREAD

**Issue by mbroadst** [stevenshiau/clonezilla#25]
Hi,
We are currently using clonezilla to provide an iso for an appliance thats easy for users to install from a usb stick (for example), however the process of creating the iso is rather cumbersome. We have a rather complicated setup using the instructions for a [customized clonezilla](http://clonezilla.org/advanced/customized-clonezilla-live.php) which needs to take our raw disk image, mount it as the root drive of a qemu instance, and then run the clonezilla iso creation scripts from the clonezilla live iso.

Is there a simpler way to do this? Especially if we keep the clonezilla version the same it seems to me we should only need to swap out the "payload" of the resulting disk image instead of having to run this process every time. Or more specifically: is there any way to quickly bootstrap a clonezilla recovery installer given a preexisting raw disk image?

Thanks!

**Comment by stevenshiau** [comment]
If your commands can be done by the Clonezilla-related boot parameters, then you can follow this:
http://clonezilla.org/show-live-doc-content.php?topic=clonezilla-live/doc/05_Preseed_options_to_do_job_after_booting
http://clonezilla.org/fine-print-live-doc.php?path=./clonezilla-live/doc/99_Misc/00_live-boot-parameters.doc#00_live-boot-parameters.doc

If you need to do more than that, you can follow this:
http://drbl.org/faq/fine-print.php?path=./2_System/81_add_prog_in_filesystem-squashfs.faq#81_add_prog_in_filesystem-squashfs.faq
If you have to make it as an iso file, then you can refer to this:
http://drbl.org/faq/fine-print.php?path=./2_System/87_create_clonezilla_iso_from_zip.faq#87_create_clonezilla_iso_from_zip.faq

Steven

**Comment by mbroadst** [comment]
@stevenshiau yeah it actually involved building a custom clonezilla iso that baked in the boot parameters - there didn't seem to be any way to do that automatically just with booting the image in qemu. Thanks!
