### ISSUE TITLE
Clone LUKS partition

### ISSUE THREAD

**Issue by piegamesde** [stevenshiau/clonezilla#32]
I have an encrypted partition `dev/sdXY` and it is decrypted to `/dev/mapper/luks-XYZ`. How can I back up that one instead of the encrypted one? It doesn't show up anywhere on the lists of available partitions. I can't afford to back up 200GiB of free space on my partition just because it is encrypted.

**Comment by sjal** [comment]
First of all - what's the point of having encrypted partition that you have unencrypted copy of?

**Comment by piegamesde** [comment]
The backup itself may be unencrypted, but the partition it will land on is LUKS encrypted again. This way, I avoid double encryption and more importantly: I do not have to back up the whole volume. Normally, CloneZilla only stores actively used nodes so the backup is as big as the partition to back up is full. But with encrypted partitions, there is no way to tell between junk and used data so CloneZilla will have to copy the whole partition which I cannot afford.

**Comment by HorstBaerbel** [comment]
Currently the backup of encrypted partitions is as big as the partition itself...
It would be nice to let CloneZilla [mount encrypted partitions through LUKS / dm-mod](https://www.errietta.me/blog/luks-clonezilla/). This way you could save a lot of space backing them up. You can store whole backup encrypted using CloneZilla, so there's no problem with plain data. This would make the backup slower, but smaller.

**Comment by stevenshiau** [comment]
Thanks for your suggestion. We will try to make it in the future.
Of course, patches are welcome.

**Comment by HorstBaerbel** [comment]
Please close the issue section here. People can still create new issues...
