### ISSUE TITLE
Working documentation for PXE boot

### ISSUE THREAD

**Issue by sRlinux** [stevenshiau/clonezilla#34]
Can some please add an working howto for PXE boot? This is https://clonezilla.org/livepxe.php is really shitty. I cant get it running with this information. then i tried the DRBL version, but i think i will become eye cancer if i use it any longer.

**Comment by stevenshiau** [comment]
Just google "PXE boot Linux" and you can find some useful info. If you still can not understand that, find someone who is familiar with that to help you.
