### ISSUE TITLE
OCS-RESIZE-PART Resize Doesn't Work on FAT32

### ISSUE THREAD

**Issue by MaDaTyGo** [stevenshiau/clonezilla#41]
When using `ocs-resize-part` found in the Ubuntu 18.04-based version of Clonezilla, it will not actually resize a FAT32 filesystem restored to a larger partition than it was captured from - it only prints out the `fatresize` information.

The `ocs-resize-part` script uses a single call to `fatresize` with both -i (information) and -s (resize) flags on the command line.  When I execute the exact `fatresize` line from the script only information is printed (no resize is attempted).  When I execute the same command line sans the -i flag, the resize occurs properly.

I would suggest either: (1) removing the -i flag from the current `fatresize` command in the `ocs-resize-part` script, or (2) removing the -s flag from the current line and adding a new `fatresize` execution below it with the -s.  The first suggestion will simply execute the resize without any fuss.  The second will still print out information before resizing.

**Comment by stevenshiau** [comment]
Thanks. The option "-i" was removed from fatresize command.
BTW, we have moved git repository to gitlab. The repository on github will not be updated anymore. As described here:
https://clonezilla.org/related-links/

Steven
