### ISSUE TITLE
Clonezilla wont use 10gbe ethernet - Only getting 1 gigabit speed for clone and recovery.

### ISSUE THREAD

**Issue by queglay** [stevenshiau/clonezilla#43]
When cloning, my speeds are not exceeding 1 Gbit/s with 10 Gbe cards.  I have also tested bonding, since they are dual port cards on either side, and this has not provided any benefit.  but I think more importantly, it would be good to see the card's 10 Gbe performance be utilised.   They normally work in Linux and Windows without any extra drivers required.

I have intel 10 Gbe NIC's in a z8 workstation and in a Qnap tvs 671 NAS.  During normal operation with nfs mounts, and smb tests I can achieve around 400 MBytes/s read and write.  clonezilla wont go much past 100MB/s

**Comment by stevenshiau** [comment]
This is Linux kernel and hardware support issue. Which version of Clonezilla live did you try? Have you tried the testing Clonezilla live? It comes with newer Linux kernel so your hardware might be supported better.

Steven

**Comment by queglay** [comment]
Thanks for the reply Steven.
I tried a few different iso's, but this one was the first that I had success with -
clonezilla-live-20180812-bionic-amd64.iso

**Comment by stevenshiau** [comment]
OK, thanks for your feedback. I am closing this now.

**Comment by queglay** [comment]
apologies, what i mean was that was the only iso that I was able to clone with at all.  but the issue is still present.

**Comment by ValdikSS** [comment]
Do you use compression? Default parallel gzip gives 150 MB/s at most on restore on my hardware. Try to disable compression in advanced parameters.

**Comment by queglay** [comment]
Thanks for the suggestion.  Though I'm running another test now without compression.  It's pulling around 80 MB/s
