### ISSUE TITLE
stable/stable-alternate -- no UEFI bootable images since zesty

### ISSUE THREAD

**Issue by huang-jy** [stevenshiau/clonezilla#47]
As title suggests, since Zesty (**clonezilla-live-20170905-zesty-amd64.iso**), the stable-alternate images will not boot on a UEFI machine (I'm using a MacBook as test)

You can tell if an image will boot by popping the USB into a Linux machine and checking the partitions list. A UEFI bootable disk will show a OCS-EFI partition

For example: this one will boot (**clonezilla-live-20170905-zesty-amd64.iso**):

![image](https://user-images.githubusercontent.com/2756283/56943089-d5fb1d00-6b15-11e9-8406-4dc68652dd04.png)

This one will not (clonezilla-live-2.6.1-25-amd64.iso):
![image](https://user-images.githubusercontent.com/2756283/56943503-ae0cb900-6b17-11e9-9a43-88629742d7dc.png)

From the stable set of images, the last one that will boot is **clonezilla-live-2.5.2-31-amd64.iso**

While it is possible to hack the image using something like this: https://www.rmprepusb.com/tutorials/136_uefi_ubuntu, some people won't have the time or desire to have to hack something that should just work.

**Comment by stevenshiau** [comment]
I can successfully boot Clonezilla live 2.6.1-25 amd64 on my MacBook Pro, and Mac mini. How did you put Clonezilla live on your USB stick?
I downloaded Clonezilla live 2.6.1-25 amd64 zip file, and follow 
https://clonezilla.org/liveusb.php
to put it on USB flash drive.

Steven

**Comment by huang-jy** [comment]
I use `dd` to burn the iso image from a linux box, which is the same way I've always done it for all isos (not just clonezilla) and is generally the universal way of writing disk images on linux.

I also used the linux-based "disks" utility to "restore disk image" which probably uses dd under the hood.

On using a clonezilla image that has an ocs partition, I see something like this:

![image](https://user-images.githubusercontent.com/2756283/57068294-35e5f500-6cc9-11e9-927d-ea29892f7acf.png)

(image from https://www.makeuseof.com/tag/how-to-boot-a-linux-live-usb-stick-on-your-mac/ but serves the purpose)

On using an image that doesn't have an OCS partition, I don't get the EFI boot option

**Comment by stevenshiau** [comment]
Please try the method I mentioned (use zip file), since it's tested by us. "dd" way to put iso file on USB flash stick is not OK for uEFI booting.

Steven

**Comment by huang-jy** [comment]
Okay, so using the method of the zip contents _kind of_ worked.

When using a FAT/NTFS filesystem on the usb disk, the makeboot script uses syslinux and that then shows up on the Mac boot menu.

However, when using an ext4 filesystem instead, which although not mentioned on the page, appears to be supported according to the makeboot script, as it mentions "ext2/3/4", it then uses extlinux instead of syslinux and that _doesn't_ show up on the boot menu. Not so much of an issue, just means we need ti remember to flash using a FAT filesystem instead of ext.
