### ISSUE TITLE
Missing dependency control in deb package

### ISSUE THREAD

**Issue by PeterDaveHello** [stevenshiau/clonezilla#49]
Clonezilla installed on Ubuntu 18.04 from default apt repository, version: `3.27.16-2`

compression option:
`-z5p Use_parallel_xz_compression,_for_multicore/CPU`

Missing dependency:

`pixz`:
```
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Run partclone: partclone.vfat -z 10485760 -L /var/log/partclone.log -c -s /dev/mmcblk0p1 --output - | pixz -3 | split -a 2 -b 4096000MB - /home/partimag/2019-08-03-test/mmcblk0p1.vfat-ptcl-img.xz. 2> /tmp/split_error.SomHkb
/usr/share/drbl/sbin/ocs-functions: line 1248: pixz: command not found
```

`screen`:
```
ocsroot device is local_dev
Preparing the mount point /home/partimag...
If you want to use USB device as a Clonezilla image repository, please
 * Insert USB device into this machine *now*
 * Wait for about 5 secs 
 * Press Enter key 
so that the OS can detect the USB device and later we can mount it as /home/partimag.
Press "Enter" to continue......
/usr/sbin/prep-ocsroot: line 48: type: screen: not found
Mounting local dev as /home/partimag...
```

I took a look at https://github.com/stevenshiau/clonezilla/blob/master/debian/control#L13, maybe `pigz` is also missing?

Not sure if you'd like to update the dependency here directly, though I install a version from Ubuntu repository, but the missing dependency looks on both side.

BTW, just FYI, this is the dependency of Clonezilla package in Ubuntu 18.04 repository, maybe you'd like to take it as a reference:
```
Depends: drbl, file, pigz, gdisk, bc, dialog, fdisk | util-linux (<< 2.29.2-3~), e2fsprogs
```

Thanks you!

**Comment by stevenshiau** [comment]
As described here:
https://drbl.org/installation/02-install-required-packages.php
You have to run "sudo drblsrv -i" to configure the system, and the required packages will be installed. Of course, it's better to put the required packages in the Depends. However, in the program, if pixz is not found, xzcat will be used in your case. No idea why it fails.
BTW, please use 
httsp://gitlab.com/stevenshiau/clonezilla
or sourceforge forum:
https://sourceforge.net/p/clonezilla/discussion/
in the future. This github repository is not maintained anymore.
Thanks.

Steven

**Comment by PeterDaveHello** [comment]
Oh, thanks!
