### ISSUE TITLE
Failed to create initrd in the restored os

### ISSUE THREAD

**Issue by madjoe** [stevenshiau/clonezilla#50]
I've restored my very first partition by using CloneZilla. However, during the process, I've noticed an error message: `Failed to create initrd in the restored os`. Since my Manjaro works fine now and I assume I could just ignore that message, I'd like to double check if I any further actions should be applied?

**Comment by stevenshiau** [comment]
In that case, you can ignore that error message, and if it's required, use the update initrd utility to do that in your Manjaro.

Steven

**Comment by madjoe** [comment]
Just to wrap up this properly for people out there who may end up here after encountering the same issue... the following will resolve it. You may run this in your Konsole, or TTY.:

```
sudo mkinitcpio --preset linuxXY
```

where **X** and **Y** are your major / minor linux version.
