### ISSUE TITLE
奇怪的问题真机

### ISSUE THREAD

**Issue by marklove5102** [stevenshiau/clonezilla#53]
系统是由UltraISO写u盘装的
Win10_20H2_v2_English_x64.iso
磁盘是 Win10_20H2_v2_English_x64 分区的。

两个不同的硬盘都是这种问题。
有一个硬盘只有一个分区（win10）无系统保留分区
clonezilla.log：
Starting /usr/sbin/ocs-sr at 2021-03-18 10:30:07 UTC...
*****************************************************.
Clonezilla image dir: /home/partimag
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
The selected devices: sdb1 sdb2
PS. 下次您可以直接下这样的指令:
/usr/sbin/ocs-sr -q2 -c -j2 -z1p -i 4096 -sfsck -scs -senc -p reboot saveparts 2021-03-18-10-img sdb1 sdb2
*****************************************************.
The selected devices: sdb1 sdb2
这个磁盘存在不匹配的GPT和MBR分割表: /dev/sdb
这将会搞混再生龙，使得产生的镜像文件无法使用，或者无法复制磁盘。
你可以使用gdisk或者sgdisk来修复这个问题。例如，如何你确认MBR分割表才是你要的，你可以使用这个指令来将GPT的分割表清除，而保留MBR分割表:
sudo sgdisk -z /dev/sdx
相反的，若你确认只有GPT分区表是你要的，你可以使用这个指令将MBR分区表清除，而保留GPT分区表:
sudo dd if=/dev/zero of=/dev/sdx bs=512 count=1
//注意// (1) 将/dev/sdx取代成上述的磁盘名称 (2) 磁盘上的资料有可能会全部丢失，因此请务必小心使用此指令。
请修复此问题然后再启动再生龙。
程序停止!!

**Comment by stevenshiau** [comment]
The solution has been described as its prompt:
这个磁盘存在不匹配的GPT和MBR分割表: /dev/sdb
这将会搞混再生龙，使得产生的镜像文件无法使用，或者无法复制磁盘。
你可以使用gdisk或者sgdisk来修复这个问题。例如，如何你确认MBR分割表才是你要的，你可以使用这个指令来将GPT的分割表清除，而保留MBR分割表:
sudo sgdisk -z /dev/sdx
相反的，若你确认只有GPT分区表是你要的，你可以使用这个指令将MBR分区表清除，而保留GPT分区表:
sudo dd if=/dev/zero of=/dev/sdx bs=512 count=1
//注意// (1) 将/dev/sdx取代成上述的磁盘名称 (2) 磁盘上的资料有可能会全部丢失，因此请务必小心使用此指令。
请修复此问题然后再启动再生龙。
