### ISSUE TITLE
How to proceed when cloning a hard disk to another one for new PC?

### ISSUE THREAD

**Issue by omexlu** [stevenshiau/clonezilla#57]
Hello,

How to proceed when cloning a hard drive to a new larger hard drive for a new PC?

I use Ubuntu 20.04 as OS.

What must be done after the restore?

Does clonezilla take over the changes to the boot and fstab?

How exactly do you have to do this?

Thanks in advance.

**Comment by stevenshiau** [comment]
You can refer to the docs here:
https://clonezilla.org/clonezilla-live-doc.php
Especially this one:
https://clonezilla.org/show-live-doc-content.php?topic=clonezilla-live/doc/03_Disk_to_disk_clone
If you want to let Clonezilla to expand the partitions proportionally for you, remember to enter expert mode, and choose the option "-k1":
https://clonezilla.org/clonezilla-live/doc/03_Disk_to_disk_clone/advanced/05-advanced-param.php

Steven

**Comment by omexlu** [comment]
Thank you, also my idea works without problems? 😉

**Comment by stevenshiau** [comment]
Basically the answer is yes. However, you will only know after you use it.
//NOTE// Backup important data before you use Clonezilla. Just in case.

Steven

**Comment by omexlu** [comment]
Strange that the new disk will have the same uid, but thank you :)

**Comment by stevenshiau** [comment]
Sure. It's "cloning", so the UUID definitely is exactly the same.

Steven

**Comment by omexlu** [comment]
Cool 👍 so my idea will certainly working, just need to plug-out the old disk after finish and first booting the new disk :)

PS. Have you any experience with ssd to nvm-chips?

**Comment by stevenshiau** [comment]
Yes, remember to remove the old one  from the machine before you boot  it with the cloned OS. Otherwise your OS will be confused since same UUIDs exist.

As for ssd to nvm-chips, it should be OK if your Ubuntu 20.04 has the driver to support it.

Steven

**Comment by omexlu** [comment]
Many thanks to you :)
