### ISSUE TITLE
Feature request: BitLocker support for home folder

### ISSUE THREAD

**Issue by fiddyschmitt** [stevenshiau/clonezilla#58]
Hi Steven,

When I select a BitLocker partition to use as the home folder, it says 'Unknown file system type: BitLocker'.

Could Clonezilla be updated to detect BitLocker partitions, and mount them using:

```
mkdir -p /media/bitlocker
dislocker <partition> -u -- /media/bitlocker    //this will prompt for a password
mount -o loop /media/bitlocker/dislocker-file /home/partimag
```

Thank you,
Fidel

**Comment by stevenshiau** [comment]
We have implemented this in the git repository. It will be used in the next testing Clonezilla live.
Thanks for this suggestion.

Steven

**Comment by fiddyschmitt** [comment]
Amazing! Thanks Steven!

**Comment by stevenshiau** [comment]
Please give testing Clonezilla live >= 2.7.3-3 or 20210621-* a try:
https://clonezilla.org/downloads.php
Please let us know the results. Thanks.

Steven

**Comment by fiddyschmitt** [comment]
Tested & worked perfectly! Thanks again Steven, this is fantastic.

**Comment by stevenshiau** [comment]
OK, great. Thanks for your confirmation.

Steven
