### ISSUE TITLE
live-media-path is being ignored

### ISSUE THREAD

**Issue by JDFandango** [stevenshiau/clonezilla#59]
Hi,

I'm using a custom live Clonezilla boot USB device. I have moved my /live folder to a custom location and used the boot parameter live-media-path (along with boot=live). On booting, Clonezilla complains it can't find the squashfs file.

Looking at this line of the script:
https://github.com/stevenshiau/clonezilla/blob/89dc7273937e688c62ba32d25944fc74e984e3fb/scripts/sbin/ocs-functions#L10768

You don't appear to use this information once you have it, which is why I believe I'm having this issue.

Please let me know if i'm doing something wrong, or if you are able to fix this.

Thanks,

Jamie

**Comment by stevenshiau** [comment]
Thanks for reporting this issue. We have fixed it and committed to the git repository. It will be used in the next testing Clonezilla live release.

Steven

**Comment by stevenshiau** [comment]
Please give testing Clonezilla live >=2.8.0-3 or 20210907-* a try:
https://clonezilla.org/downloads.php
Please let us know the results. Thanks.

Steven

**Comment by JDFandango** [comment]
That works, thanks!

Jamie

**Comment by stevenshiau** [comment]
Great. Thanks for your confirmation.

Steven

**Comment by yixi0110** [comment]
我在还原过程中 选择了镜像 却没有restoredisk 这个选项，而且打包镜像的时候 cloned successful以后 没有反映了

**Comment by stevenshiau** [comment]
@yixi0110 
Please file a new issue and if you can, please post in English in this issues report.
Or you can join this mailing list and use Chinese to discuss:
https://groups.google.com/g/ocs-clonezilla
In addition, please report that in details, and it would be even better to post some photos. That's easier for us to understand your issue.
Thanks.

Steven
