### ISSUE TITLE
Clonezilla does not boot up Properly 

### ISSUE THREAD

**Issue by blockcrafter21** [stevenshiau/clonezilla#65]
Hi,
i love Clonezilla but i tried to Clone my old 1tb HDD to my new 1tb SSD and Every time i try to boot Clonezilla it gives me this error![pic1](https://user-images.githubusercontent.com/72599189/151036445-bcf9d66a-c07d-4cbf-86bf-a90cf8a51283.jpg)

.
After removing both Drives and installing them into my Test Rig i get this Error
![Picture2](https://user-images.githubusercontent.com/72599189/151034811-695c82ea-bc8d-4eab-a32f-226d37fc3009.jpg)
.
Could someone please help me
?

**Comment by JonnyTech** [comment]
Either your usb drive is faulty or the data written to it is corrupt. Download the image again. Verify its checksum. Write it to a different usb drive. Try again.
