### ISSUE TITLE
External USB disks isn't detected but its partitions are

### ISSUE THREAD

**Issue by InfoLibre** [stevenshiau/clonezilla#67]
When I clone a partition or a disk and store it on an external USB disk, this external disk isn't detected by ocs-scan-disk (/dev/sdb isn't detected):

![IMG_20220214_160522](https://user-images.githubusercontent.com/3955499/153908486-c2ed1203-ba3c-40d3-b9b3-d74eab7a06da.jpg)

But even if this disk isn't detected by ocs-scan-disk, it is detected after:

![IMG_20220214_160558](https://user-images.githubusercontent.com/3955499/153908852-a6ae7cc6-afad-4f65-b99b-38300d7e89d9.jpg)

It seems ocs-scan-disk can't detect all disks.

I'm using Clonezilla Live stable debian based version 2.8.1-12, on a USB key.

**Comment by stevenshiau** [comment]
Thanks for your feedback.
Your /dev/sdb contains no partition, and it has file system ext4 on itself. Hence Clonezilla treats it as a partition.
Yes, the output of ocs-scan-disk can be confusing. We will think how to improve it. Ideas are welcome.

Steven

**Comment by InfoLibre** [comment]
Indeed, I forget to create a partition and a partition table:

![Capture d’écran du 2022-02-19 13-08-56](https://user-images.githubusercontent.com/3955499/154800164-f37a1d7f-1c51-4484-bbc2-f835b0213c13.png)

**Comment by stevenshiau** [comment]
Thanks for confirming that. So that's the way it is in Clonezilla now. 

Steven

**Comment by InfoLibre** [comment]
I don't think it's a problem if there's no table partition on my USB key. But it would be interesting if ocs-scan-disk  can detect and show it at the beginning. So, we are sure to know which disks are available.

**Comment by stevenshiau** [comment]
Thanks for your suggestion.
OK, we will try to implement this idea to ocs-scan-disk in the future.

Steven

**Comment by stevenshiau** [comment]
Please give testing Clonezilla live >= 3.1.3-24 or 20240908-* a try. It has been improved.
https://clonezilla.org/downloads.php

Steven

**Comment by InfoLibre** [comment]
It works now, thank yo very much.

/dev/sdb is well recognized:

![Capture d’écran du 2024-09-23 23-37-31](https://github.com/user-attachments/assets/b2f12bee-7133-410c-9eab-0434080c2872)

![Capture d’écran du 2024-09-23 23-38-05](https://github.com/user-attachments/assets/a794ad7f-1c75-4cd2-8ef7-229cbafbecc1)
