### ISSUE TITLE
Clonezilla does not detects image in /home/partimag in USB in unattended mode

### ISSUE THREAD

**Issue by GamingCity** [stevenshiau/clonezilla#69]
Maybe i missed something here, since this is my first time booting from usb drive and my previous work with clonezilla was using network booting and samba shares.

I created a EFI booteable USB flashdrive, with a NTFS partition (because the image files are too large for FAT32), i used rufus for this that allows for UEFI:NTFS. Then i copied all clonezilla (2.8.1-12) file inside the ntfs partition. I dropped the image folder into /home/partimag on that partition.

Now, if i do a manual restore everything works, when i have to choose the image folder i just use "skip" and it correctly detects the /home/partimag on the pendrive and the images inside. I copied the commands for the unattended restore that clonezilla gave me and i added them to a grub entry.

menuentry "Clonezilla Auto Restore"{
  search --set -f /live/vmlinuz
  $linux_cmd /live/vmlinuz boot=live union=overlay username=user config components quiet noswap edd=on nomodeset enforcing=0 noeject locales="es_ES.UTF-8" keyboard-layouts="us" ocs_live_run="ocs-restore-mdisks -a poweroff -p '-g auto -e1 auto -e2 -r -j2 -c -icds -scr -p true' diskimage sda sdb sdc sdd sde sdf sdg sdh nvme0n1 nvme1n1" ocs_live_extra_param="" ocs_live_batch="no" vga=788 ip= net.ifnames=0  nosplash i915.blacklist=yes radeonhd.blacklist=yes nouveau.blacklist=yes vmwgfx.enable_fbdev=1
  $initrd_cmd /live/initrd.img
}

-i want to restore image to al connected drivers (except the pendrive that i think clonezilla would auto exclude it but i wasnt able to test this yet)-

But this just stops saying that "/home/partimag/diskimage" folder does not exist. And is really weird because i never had this issue of the commands that clonezilla gives me for unattended not working.

**Comment by stevenshiau** [comment]
It's recommended to have 2 partitions on your USB drive. The 1st one is for Clonezilla live (you can use FAT32), and the 2nd one is for the image repository (You can use NTFS). Then you can use something like (assume that your image repository is /dev/sdf2):
ocs_repository="dev:///dev/sdf2"
to mount the image repository.
Ref: 
https://clonezilla.org/fine-print-live-doc.php?path=clonezilla-live/doc/99_Misc/00_live-boot-parameters.doc

Steven

**Comment by GamingCity** [comment]
But i cant be sure were the image repository is because that changes depending on the number of sata disks conected.
It could be sda1... or sdb1... etc
When i do it manually, after selecting skip, it correctly detects the boot disk ID and partition number were the repository is and mounts it on "/run/live/medium". But that does not happens in unattended mode.

I think it has to work using label or UUID to point clonezilla to the right disk/partition, but im not sure why there is a diference from manual to unattended in this case.

**Comment by GamingCity** [comment]
OK, i checked using cmd and i relised that "/run/live/medium" was correctly mounted, but somehow, using unattended it does not checks for images in "/run/live/medium/home/partimag" like it does in manual restore.

So i solved it by adding a symb link 
ocs_prerun="ln -s /run/live/medium/home/partimag/Image /home/partimag"

But im not sure why this is only needed in unattended, there is a missing command?

**Comment by GamingCity** [comment]
got it, thank you.
