### ISSUE TITLE
Here a script to create a bootable USB stick on OSX

### ISSUE THREAD

**Issue by daccle** [stevenshiau/clonezilla#7]
Hi! 

I just wrote a USB installer for OSX. Maybe this can help people to use Clonezilla. 
https://github.com/daccle/osx_clonezilla_usb_installer

Best, Daniel

**Comment by stevenshiau** [comment]
@daccle 
Got it. Thanks.
I am thinking what's the best way to share this to Clonezilla live users... Any suggestion?

Steven.
