### ISSUE TITLE
Disc-To-Disc SSD Painfully slow

### ISSUE THREAD

**Issue by BusterTheBusta** [stevenshiau/clonezilla#80]
My higher-up ordered me to find and try out data cloning software to easily install ready-made setup to work computers and laptops. For that he gave me 2 Laptops, and 1 "Shell" to insert one NVMe SSD into and then connect it per USB with one of the Laptops. 
I followed the guide on the website, chose beginner mode with devive-to-device, and then it started to do the copying. At first it was fast at around 10Gbits/s but then the transfer rate started to go down and down and now we're at around 45MBits/s a week later and at ~50% done in total. I first suspected maybe it was thermal throttling on one or both SSDs, but a more knowledged co-worker said it's probably more that the cache is overrun and full. 

If you look at the screen, it says that the filesystem is raw, and thus using dd and full disc-to-disc copying, which is weird because both drives had Windows installed so it should automatically detect it as NTFS. For some reason the free-space field for the source says that none is left, but said Windows install only takes 80Gb from 1TB. I originally thought that the program failed to see the Filesystem as NTFS because the destination drive was in that special shell connceted through USB-C, but my higher-up correctly said, that the controller on that thing should do it's job. 

I read the Documentation, but I didn't find a way to manually set and define the source filesystem or such for smart-cloning. Is there a way I can avoid this for future setups? My only Idea is shrinking the entire source drive to just the Windows partition and just clone that partition and then restore...

**Comment by stevenshiau** [comment]
Have you tried to save the source machine as an image, then restore it? 
BTW, if possible, please show /var/log/clonezilla.log. It contains more info.

Steven

**Comment by BusterTheBusta** [comment]
I found one quick workaround a week or so ago. I think it was by shrinking the source partition with the Windows install to it's minimum, leaving the rest unallocated & unformatted and then doing the device-to-device copy to the other SSD. 

I will try to retrieve the log file you mentioned on Tuesday when I'm back at work.

**Comment by BusterTheBusta** [comment]
Good evening. Unfortunately, because the log file is created and accessible while the initial boot is still loaded, it is now long lost. I think this Issue can be closed.
