### ISSUE TITLE
Hang on "Saving hardware info by lshw..."

### ISSUE THREAD

**Issue by Deleetdk** [stevenshiau/clonezilla#82]
Using current live/USB stable (3.0.2-21-amd64) and current beta (3.0.3-1-amd64).

I'm trying to clone a 256GB SSD with Windows on it from an older computer, from approximately 2007, into a Dell 7706 3-in-1 4TB Nvme. I'm encountering a weird hang bug. Searching around, I find several other people over the years who had this:

- https://sourceforge.net/p/clonezilla/bugs/303/
- https://sourceforge.net/p/clonezilla/discussion/Clonezilla_live/thread/f04990e2/
- https://sourceforge.net/p/clonezilla/discussion/Clonezilla_live/thread/4c57bfb1/
- https://ubuntuforums.org/showthread.php?t=2304259

![lshw](https://user-images.githubusercontent.com/6759913/209858746-a3040a08-b090-412b-a52f-65604da8bf92.jpeg)

There are three offered solutions:

1. Use an older version, clonezilla-live-2.4.9-17-i686-pae. I tried the amd64 version of this, and it fails to reach the main screen:

![clonezilla start](https://user-images.githubusercontent.com/6759913/209858804-91e0bf27-dd29-44f0-984a-1cd899a997cb.jpeg)

I also had to disable secureboot in the BIOS to reach this stage.

2. Change the disk clutersize to match. I don't know how to accomplish this. Is this a good idea?

3. Edit the "/usr/share/drbl/sbin/ocs-functions" file to change a function to avoid calling `lshw`. This file doesn't exist in my ISO. Must be an old version?

![clonezilla 3 0 3 1](https://user-images.githubusercontent.com/6759913/209859533-2a6ce442-f5d2-4fca-b9f5-956627fd5609.png)

How do I go from here?

**Comment by stevenshiau** [comment]
Sometimes this is related to Linux kernel/hardware support issue.
Have you tried Ubuntu-based Clonezilla live? E.g., 20221230-*?
https://clonezilla.org/downloads.php

Steven

**Comment by Deleetdk** [comment]
I was able to copy the system by using the other computer, and using the Ubuntu version. Not sure which did the trick. After this, the system failed to boot, and I was unable to recover it using the various windows tools, so it was ultimately not a success. Sigh!

**Comment by stevenshiau** [comment]
Sorry to hear that.
When you save the image, Clonezilla should not touch your source disk, unless it triggers some hardware related issues and makes your system fail to work. It might happen, but should be very seldom. 

Steven

**Comment by Deleetdk** [comment]
I meant that the destination failed to boot after copying. The source is intact and works.

**Comment by stevenshiau** [comment]
You have to make sure the restored destination machine has the same hardware with the source one. For MS Windows, this is important. Or you have to install sysprep from MS in the source machine before you take an image, it might help.

Steven
