### ISSUE TITLE
DELL 3050 AIO's stopped working after cloning from lite server

### ISSUE THREAD

**Issue by TerraGitHuB** [stevenshiau/clonezilla#83]
Hi y'all,

I've had a problem that seems quite significant, and since it happened after using clonezilla, I wondered whether anyone would be able to shed any light on the situation...

So we wanted to clone a specific drive to several machines. One of them was used for a lite server, and we cloned to 9 other machines that are identical.

One of the machines was fine (we had started cloning to just that machine, then cancelled to accommodate for more lite clients), however after rebooting, 8 out of the nine wouldn't even POST. 

We've tried resetting the BIOS, and taking out the disks, to no avail.

I imagine it's probably an issue with these machines, but wanted to ask in the event someone knew anything.

Thanks.

**Comment by stevenshiau** [comment]
"8 out of the nine wouldn't even POST" -> What were the messages on the screen? Could you please take some photos and share them?

**Comment by TerraGitHuB** [comment]
No messages, just a DELL Logo. If you press F12, it does show the message (Loading One-time boot menu), but it never get's anywhere. Also responds to ctrl+alt+del

**Comment by JonnyTech** [comment]
Is the boot mode on the computers BIOS/MBR or UEFI/GPT?

**Comment by stevenshiau** [comment]
Which version of Clonezilla live did you use? 
I remembered there was a bug for older package that might break the BIOS of Dell machine:
https://sourceforge.net/p/clonezilla/bugs/310/
However, that was several years ago...

Steven

**Comment by TerraGitHuB** [comment]
We just used alt-stable from the clonezilla website.

Thanks for that thread though. These machines are from that kind of time period, and as far as I know, the BIOS has never been updated. Unfortunately, I think the rest of the group aren't so keen on using clonezilla anymore, so I doubt we'll be testing it again. Still, interesting to note, and we may end up using the work arounds posted in that thread. 

Thanks to all
