### ISSUE TITLE
Missing French (Switzerland) keyboard layout

### ISSUE THREAD

**Issue by defdefred** [stevenshiau/clonezilla#85]
Only German (Switzerland) is available...

Thanks!

**Comment by defdefred** [comment]
Ok I can choose "French (Switzerland)" in the next screen :-)
Please create a "Switzerland" entry instead of  "German (Switzerland)".
It will be less disturbing :-)

**Comment by stevenshiau** [comment]
We actually use:
dpkg-reconfigure keyboard-configuration
to do that. It's from our upstream, Debian Linux.
Hence please report it to Debian:
https://packages.debian.org/sid/keyboard-configuration
Thank you very much.

Steven

**Comment by defdefred** [comment]
Ok thanks.
I don't have the issue when installing Debian...

**Comment by stevenshiau** [comment]
I believe you meant installing stable Debian. However, Clonezilla live is based on unstable Debian (Sid). It's might be a bug for the keyboard-configuration in Sid.

Steven
