### ISSUE TITLE
clonezilla-live-20221103-kinetic-amd64.iso  ocs-live-netcfg /etc/resolv.conf: No such file or directory

### ISSUE THREAD

**Issue by m2acgi** [stevenshiau/clonezilla#87]
**clonezilla-live-20221103-kinetic-amd64.iso** 执行 `ocs-live-netcfg` 后报错: 

```
/usr/sbin/ocs-live-netcfg: line 234: /etc/resolv.conf: No such file or directory
```

经过查看，是 symbolic link  `/etc/resolv.conf` 所指向的真实文件不存在。

**Comment by stevenshiau** [comment]
Thanks for reporting this issue. It's fixed. If any issue, please reopen it.
