### ISSUE TITLE
efibootmgr output has changed, breaking the regex in get_efi_hd_boot_entry_info()

### ISSUE THREAD

**Issue by johnv-valve** [stevenshiau/clonezilla#9]
In clonezilla-live-2.4.2-10-amd64, efibootmgr version 0-12.1 appears to have changed its output formatting and this breaks the regexes used by osc-functions:get_efi_hd_boot_entry_info().

efibootmgr version 11:
```
BootCurrent: 0000
Timeout: 1 seconds
BootOrder: 0000
Boot0000* steamos	HD(1,800,f3800,b1a1b6ea-3938-4d00-be43-50f768c6f589)File(\EFI\steamos\grubx64.efi)
```
efibootmgr version 12:
```
BootCurrent: 0000
Timeout: 1 seconds
BootOrder: 0000
Boot0000* steamos	HD(1,GPT,b1a1b6ea-3938-4d00-be43-   50f768c6f589,0x800,0xf3800)/File(\EFI\steamos\grubx64.efi)
```

Note the change from "800,f3800" in v11 to "GPT" in v12

**Comment by stevenshiau** [comment]
@johnv-valve,
Thanks for the bug report. It's fixed.

Steven.
